# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter

name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '💥 Breaking Changes'
    label: '💥 Breaking Change'

  - title: '🌟 New Features'
    label: '🌟 New Feature'

  - title: '⭐ Features'
    label: '⭐ Feature'

  - title: '🐞 Bug Fixes'
    label: '🐞 Bug Fix'

  - title: '🛠 Improvements'
    label: '🛠 Improvement'

  - title: '📖 Documentation'
    label: '📖 Docs'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes'
template: |
  $CHANGES
  ***
  For full changes, see the [comparison between $PREVIOUS_TAG and v$NEXT_MINOR_VERSION](https://github.com/newbe36524/Newbe.Mahua.Framework.V1/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION)
exclude-labels:
  - 'Skip Release'